### ISSUE TITLE
Mac OS X build fail

### ISSUE THREAD

**Issue by mikeyearworth** [USEPA/OME#2]
Hi,

When trying to Build All on Mac OS X (10.11.6) using Xcode 8.2.1 I get the following error

`error: /Users/pwingo/Programming Projects/ome-unstable/CompiledHeaderTemplate.txt: No such file or directory`

apparently when trying to do:

`PBXCp /Users/pwingo/Programming\ Projects/ome-unstable/CompiledHeaderTemplate.txt /Users/XXXX/Library/Developer/Xcode/DerivedData/OME_OSX-fnhuwoizujfvnkhhsrkjlqjtfbdh/Build/Products/Debug/CompiledHeaderTemplate.txt
    cd /Users/MY304/Public/Software/OME/project_files/OS_X/OME
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/pwingo/Programming\ Projects/ome-unstable/CompiledHeaderTemplate.txt /Users/XXXX/Library/Developer/Xcode/DerivedData/OME_OSX-fnhuwoizujfvnkhhsrkjlqjtfbdh/Build/Products/Debug`

any clues? My build location is `/Users/XXXX/Public/Software/OME` and I'm assuming that reference to your build path `/Users/pwingo/Programming\ Projects/ome-unstable/` shouldn't be in the there? I cloned the distribution using git this morning.

Interest in the OME engine arising from reading
Wingo, P., Brookes, A., & Bolte, J. (2017). Modular and spatially explicit: A novel approach to system dynamics. _Environmental Modelling and Software_, 94, 48-62. doi: 10.1016/j.envsoft.2017.03.012

Mike

Prof Mike Yearworth
Professor of Management Science
Centre for Simulation, Analytics & Modelling (CSAM)
Business School
University of Exeter 
Tel: +44 (0)1392 722133
Mob: +44 (0)7789 692266

**Comment by justaPCWingo** [comment]
Hi. I'm the the one who put the project file together that you are attempting to use. I'm no longer affiliated with the EPA, but I figured I should chime in, seeing how there's still a file path from my computer in the project file. 

The error is from an extra "copy files" step that is no longer needed. To fix, the copy phase needs to be removed:

1. Open the project workspace in XCode.
2. Select the OME project in the left column (file navigator).
3. Select "ModelClassBuilder" from the vertical Targets List.
4. Click on "Build Phases" in the horizontal titles/tabs.
5. Expand the Copy Files list item. Highlight the "CompiledHeaderTemplate.txt" entry and press the delete key.

This should be enough to get past this issue. However, there may be some other build issues introduced with updates to the Clang compiler in XCode, or some issues that I straight up missed (such as this issue). I'm happy to help you work through any additional build issues you encounter, but I may be slow to respond due to other obligations.

You can also try the build system for Windows if that is available to you. All the project files target Visual Studio 2013, but should be compatible with 2015/2017 as well.

**Comment by mikeyearworth** [comment]
Dear Patrick,

Thanks for getting back to me and for the fix to the CompiledHeaderTemplate.txt problem. I've now run into a problem with a missing header file - RunConsoleController.h is not found when trying to #import in RunConsoleController.m

Best
Mike

**Comment by justaPCWingo** [comment]
Hmm. It looks like that file did not make it in to the git Repo during a reorganization. I've added the header file to the repository; try pulling the repository down again (git pull or the zip file) and building.

**Comment by mikeyearworth** [comment]
I still can't see it. I pulled the repository and started from scratch. Same error. I then searched on the repository - it's not there!

<img width="1028" alt="screen shot 2017-12-17 at 19 34 38" src="https://user-images.githubusercontent.com/12748225/34083067-fed9c5c4-e361-11e7-820b-cfc0614fec0c.png">

**Comment by justaPCWingo** [comment]
That's because I missed a step with adding the missing file to the repo. I've uploaded it and confirmed that its in the repository. Please give it another shot when you have the chance.

**Comment by mikeyearworth** [comment]
Build All now succeeds.
Many thanks
